### ISSUE TITLE
Bluetooth headset play/pause button

### ISSUE THREAD

**Issue by ludmar-ribeiro** [anickle060193/easy_control#124]
Hi.  

I would love to play and pause the playing media with the play button present on my Bluetooth headset.

Lud Ribeiro

**Comment by anickle060193** [comment]
I think this is a bit outside the scope of the extension. I think you would have to setup your bluetooth headset and computer so that the play button on the headset is interpreted as a play key press by your computer. Then you would setup the extension to use that key press to activate the shortcut like any other key press.
